CREATE TABLE IF NOT EXISTS Personne (
  id SERIAL PRIMARY KEY,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  telephone INT NOT NULL UNIQUE,
  identifiant TEXT NOT NULL,
  mdp TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);